name: github actions practice
run-name: ${{ github.actor }} is learning Github Actions
on: #Chooses an event when to run actions
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: # Jobs consist different of different steps to test/simulate something. If all steps pass, the job is successful.
  salute: # Job name
    runs-on: ubuntu-latest # Simulates an environment where the job gets executed. Here we have chosen Linux distribution called Ubuntu
    steps: # Define steps of the job
      - name: Show event type # Step name
        run: echo "Triggered by Event type ${{ github.event_name }}" # Run command runs a bash script/prompt
      - name: Say hello to person who triggered the actions!
        run: echo Hello ${{ github.actor }}!

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Acces project files in runner environment
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
      - name: Install node modules
        run: npm ci
      - name: Run tests and build the project
        run: npm test && npm run build