name: github actions practice
run-name: ${{ github.actor }} is learning Github Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  salute:
    runs-on: ubuntu-latest
    steps:
      - name: Show event type
        run: echo "Triggered by Event type ${{ github.event_name }}"
      - name: Say hello to person who triggered the actions!
        run: echo hello ${{ github.actor }}!

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Access project files in runner environment
        uses: actions/checkout@v2
      - name: Install dependencies for the runner environment
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Result
        run: |
          if npm test; then
            echo "::set-output name=result::success"
          else
            echo "::set-output name=result::failure"
            exit 1
          fi

  test-condition-check-success:
    runs-on: ubuntu-latest
    needs: test
    if: ${{  needs.test.result == 'success'  }}
    steps:
      - name: Testing succesful!
        run: echo "Unit tests passed succesfully!"

  test-condition-check-failure:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result != 'success' }}
    steps:
      - name: "Testing failed!"
        run: echo "Unit test failed"
