name: SonarCloud scan
on:
  push: 
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
        - name: Access project files in runner environment
          uses: actions/checkout@v4
        - name: SonarCloud scan
          uses: SonarSource/sonarcloud-github-action@master
          env: 
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            organization: "jerryuusis"
            projectKey: "gh_actions_practice"